### ISSUE TITLE
HELP / URGENT BUGS

### ISSUE THREAD

**Issue by Metallfunky** [BitcoinStaking/BitcoinS#1]
dear Dev BSK, 
I think 32bit BSK Wallet has serious BUGS, I have been mining by staking for 5 days
did not get anything at all, the attachment is in the image that I included

1. I have a stake of 4106 (staking asset), and the notification status under the wallet confirms me
has 4106 mature BSK coins (active)

2. When 2.5 BSK coins have been mined, my status changes (my 4106 staking asset has changed
to 0, which means I don't have MATURE Coins to mine) can be seen in the Information below
Wallet, then my COIN disappeared again after getting from mining, this incident has been frequent and long enough, and The worst thing is that it's been 5 days since I didn't get anything from mining.

what's the solution?
Please Check!

![11](https://user-images.githubusercontent.com/60968531/96838947-bcb8ff80-1472-11eb-97df-dde85a65941a.jpg)
![22](https://user-images.githubusercontent.com/60968531/96838961-c2aee080-1472-11eb-8a95-f21d49394f51.jpg)

**Comment by BitcoinStaking** [comment]
This is normal behavior. Transactions need 500 confirmations to become mature. Since you have a small amount of coins relative to the network, it is difficult to find a block. When you do find a block it quickly becomes orphaned because the network has created a chain with more work. 

Solution:Once you see your mined block get at least 6 confirmations, you should have a block that remains on the main chain.
